//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTienda.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyectoEntities1 : DbContext
    {
        public proyectoEntities1()
            : base("name=proyectoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asignaciones_cliente> asignaciones_cliente { get; set; }
        public virtual DbSet<autor> autor { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<ejemplar_libro> ejemplar_libro { get; set; }
        public virtual DbSet<genero> genero { get; set; }
        public virtual DbSet<libro> libro { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
